### ISSUE TITLE
Plug-in extension point(s) for express configuration

### ISSUE THREAD

**Issue by cdamus** [eclipse-emfcloud/modelserver-node#18]
Currently, the framework provides plug-in extension points for delegation of behaviour of several _Model Server_ API endpoints. However, there are some customizations that cannot be accomplished without access to the `express` app and/or routers configured in it. Of particular interest in my own application of the server are

- configuration of CORS rules, such as via the [`cors` middleware package](https://www.npmjs.com/package/cors)
- addition of routes for custom API endpoints

There is actually a mechanism for the latter via injection of `RouteProvider`s into the server, but that is an internal API. This or some refinement of it could be published to plug-ins for contribution of custom routers. For injection of middlewares something new is needed because that requires customization of routes provided by other parties, including the core. So some injectable `MiddlewareProvider` interface that `RouteProvider`s can consult to install middlewares on their routes.

**Comment by eneufeld** [comment]
So probably the easiest would be to extend the serve method of the ModelServer here: https://github.com/eclipse-emfcloud/modelserver-node/blob/4303f43338b726c24e511a68d79c16ce61c9c8ae/packages/modelserver-node/src/server.ts#L56
and allow to provide a list of `(req, res, next) => void` functions 
what do you think?

**Comment by cdamus** [comment]
> So probably the easiest would be to extend the serve method of the ModelServer here:

As the server framework is DI-based, I would prefer to contribute customizations by that mechanism than by subclassing. PR #19 is my proposal for a DI-based solution.
