### ISSUE TITLE
Add modelUri to CommandProvider

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipse-emfcloud/modelserver-node#24]
CommandProvider#getCommands is defined as:

```
getCommands(customCommand: ModelServerCommand): MaybePromise<ModelServerCommand | Transaction>
```

If a specific provider wants to access the Model to edit it, it currently needs to derive the modelURI from an object that is part of the command. For example:

```
 getCommands(customCommand: ModelServerCommand): Transaction {
        const [modelURI, elementID] = customCommand.owner.$ref.split('#');
        ...
}   
```

However, since the `owner` attribute is optional, there is no consistent way to retrieve the modelUri. Some (pre-existing) custom commands only define ID-attributes, without including the modelUri, which makes it impossible to derive the modelUri from the Command alone.

In the Java implementation of the Model Server, modelURI is always part of the API:

```
Command clientToServer(URI modelUri, EditingDomain domain, CCommand clientCommand) throws DecodingException;
```

We should add the modelUri to the `modelserver-node`'s CommandProvider, to be consistent with the pre-existing implementation. This will make it easier to migrate existing custom commands from Java to Node.

**Comment by cdamus** [comment]
I think this was fixed by PR #25. Please re-open if that is incorrect.
